config/routes.rb
Rails3Hw1::Application.routes.draw do
  resources :employees
  resources :duties, only: [:create, :destroy]

end

app/models/duty.rb
class Duty < ActiveRecord::Base
    attr_accessible :description
    validates :employee_id, presence: true
    validates :description, presence: true


    belongs_to :employee
end

app/models/employee.rb
class Employee < ActiveRecord::Base
    attr_accessible :name
    validates :name, presence: true

    has_many :duties, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
    
    def create
        if @@employee.duties.build(params[:duty]).invalid?
            #redirect_to :back
            #return
            respond_to do |format|
                format.html { redirect_to :back, notice: 'Duty can not be empty.' }
                format.json { head :no_content }
            end
            return
        end

        @duty = @@employee.duties.build(params[:duty])
       
        if @duty.save
            flash[:success] = "Duty created!"
            #redirect_to 'employee#index'
            DutiesController.set_employee(@@employee)
            redirect_to :back
        else
            render 'employees#index'
        end


    end

    def self.set_employee(employee)
        @@employee = employee
        ""
    end
    
    def destroy
        @duty = Duty.find(params[:id])
        @duty.destroy

        respond_to do |format|
            format.html { redirect_to :back, notice: 'Duty was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])
    @duties = @employee.duties.paginate(:page => params[:page])
    @duty = @employee.duties.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    #@employee.destroy
    if @employee.duties != []
      @employee.duties.each do |duty|
        duty.destroy
      end
    end
      
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/duties/_duty.html.erb
<tr>
    <td class="duty">
        <span class="description"><%= duty.description %></span>
        <td><%= button_to 'Delete', duty, method: :delete, data: { confirm: 'Are you sure?' }%></td>
    </td>
</tr>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= button_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>
<td class="main">

<td class="sidebar round">
  <strong>Duties</strong> <%= @employee.duties.count %>
</td>

<% if @employee.duties %>
  <table class="duties" summary="Employee duties">
    <%= render @duties %>
  </table>
  <%= will_paginate @duties %>
<% end %>
</tb>

<%= form_for(@duty) do |f| %>

  <div class="field">
    <%= f.text_area :description %>
    <%= DutiesController.set_employee @employee%>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3Hw1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'prototype' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>